# (C) Copyright 2021 Hewlett Packard Enterprise Development LP

apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    cronjob.kubernetes.io/instantiate: manual
  labels:
    job-name: ecr-cred-helper-manual-001
  name: ecr-cred-helper-manual-001
  namespace: common
spec:
  template:
    metadata:
      labels:
        job-name: ecr-cred-helper-manual-001
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - |-
              set -e
              export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
              export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
              export AWS_REGION=${AWS_DEFAULT_REGION}
              export AWS_ACCOUNT=${AWS_ACCOUNT}
              echo "ENV variables setup done."
              kubectl delete secret --ignore-not-found regcred
              DOCKER_PASSWORD=`aws ecr get-login --no-include-email --registry-ids ${AWS_ACCOUNT} | cut -d' ' -f6`
              kubectl create secret docker-registry regcred \
              --docker-server="https://${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com" \
              --docker-username=AWS \
              --docker-password=$DOCKER_PASSWORD
              echo "All done."
          env:
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secretAccessKey
                  name: aws-ecr-creds
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: accessKeyID
                  name: aws-ecr-creds
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  key: region
                  name: aws-ecr-creds
            - name: AWS_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: awsAccount
                  name: aws-ecr-creds
            - name: http_proxy
              valueFrom:
                configMapKeyRef:
                  name: common-services-env
                  key: http_proxy
            - name: https_proxy
              valueFrom:
                configMapKeyRef:
                  name: common-services-env
                  key: http_proxy
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  name: common-services-env
                  key: http_proxy
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  name: common-services-env
                  key: http_proxy
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  name: common-services-env
                  key: no_proxy
            - name: no_proxy
              valueFrom:
                configMapKeyRef:
                  name: common-services-env
                  key: no_proxy
          image: "quay.io/helmpack/kubectl-helm-aws:0.1.1"
          imagePullPolicy: IfNotPresent
          name: ecr-cred-helper
          resources: {}
          securityContext:
            capabilities: {}
      dnsPolicy: Default
      hostNetwork: true
      restartPolicy: Never
      serviceAccountName: commonacc
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
